# Generated by Django 5.1.3 on 2024-11-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mirrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='mirrors/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Mirror',
                'verbose_name_plural': 'Mirrors',
                'ordering': ('-id',),
            },
        ),
    ]
