# Generated by Django 5.1.3 on 2025-02-22 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_socialcontact_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='Формат номера: +998 (__) ___ __ __', max_length=20, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате: +998 (__) ___ __ __', regex='^\\+998 \\(\\d{2}\\) \\d{3} \\d{2} \\d{2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
